### ISSUE TITLE
希望能在web上增加一个设置按钮

### ISSUE THREAD

**Issue by xiaolilir** [hezhizheng/repo-image-hosting#1]
1.可以自己增加文件夹
2.可以切换上传图片的文件夹

**Comment by hezhizheng** [comment]
> 1.可以自己增加文件夹
> 2.可以切换上传图片的文件夹

Emmmmm 可以考虑下，不过短期内不会有什么大改动  这个需求建议可以试着启动多个程序，指定不同端口、文件夹路径即可，不存在的文件夹在上传图片时会自动创建 @xiaolilir
