### ISSUE TITLE
github上传失败

### ISSUE THREAD

**Issue by xiaolilir** [hezhizheng/repo-image-hosting#2]
http://xxxx.com/static/fineuploader/fine-uploader-new.min.css.map
控制台报上面的文件无法加载

**Comment by hezhizheng** [comment]
> http://xxxx.com/static/fineuploader/fine-uploader-new.min.css.map
> 控制台报上面的文件无法加载

用的是哪个版本？什么操作系统？@xiaolilir

**Comment by hezhizheng** [comment]
我用 Edge 会显示你描述的那个问题，但是并不影响上传跟其他的功能，还有更详细点的错误信息吗？比如终端有提示任何错误吗？@xiaolilir
![Snipaste_2021-03-31_22-16-42](https://user-images.githubusercontent.com/18096449/113159522-3dc0c200-926f-11eb-9109-18bdd84d9c33.png)

**Comment by xiaolilir** [comment]
@hezhizheng 用的是 v0.0.5最新的版本linux平台。我看了下还有个报错。非常有可能是这个问题。会不会是我github的token的权限给不够或者不对。
![屏幕截图 2021-04-01 095642.jpg](https://vip1.loli.io/2021/04/01/iHJjD9F6kmC4ZMs.jpg)

**Comment by hezhizheng** [comment]
在虚拟机(Ubuntu 18.04.3 LTS)跑了下 v0.0.5的版本 也是正常的

建议从以下几点排查下：

1、github token 权限可以参考以下这张图 
![image](https://user-images.githubusercontent.com/18096449/113233898-d177aa00-92d2-11eb-8312-d3e61d44a1bd.png)

2、确保仓库存已经存在有master或者main分支，上传并没有指定分支，文件会上传至默认分支(master/main)

3、可以观察下程序启动后，终端有没有错误输出 @xiaolilir

**Comment by xiaolilir** [comment]
@hezhizheng 已经好了，多谢。果然是token的权限问题。
