### ISSUE TITLE
package repo-image-hosting/bindata is not in GOROOT (/usr/local/opt/go/libexec/src/repo-image-hosting/bindata)

### ISSUE THREAD

**Issue by SmallMX** [hezhizheng/repo-image-hosting#3]
是不是少东西啊？还是我配置错了？

**Comment by hezhizheng** [comment]
// 编译/运行前请先安装 go-bindata ，请参考 https://blog.hi917.com/detail/87.html
// 执行静态资源编译命令（每次修改静态文件都需要执行）
`go-bindata -o=bindata/bindata.go -pkg=bindata ./static/... ./views/... `
@SmallMX

**Comment by SmallMX** [comment]
可以了，谢谢！
